import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  ko: {
    // 공통 네비게이션
    mypage: '마이페이지',
    logout: '로그아웃',
    login: '로그인',
    signup: '시작하기',

    // 슬라이더
    slide1_desc: 'CareLink는 건강검진 데이터를 분석하여 사용자가 자신의 건강 상태를 쉽게 이해하고 지속적으로 관리할 수 있도록 돕는 스마트 헬스케어 서비스입니다.',
    slide2_title: '건강검진 결과, 제대로 이해하고 계신가요?',
    slide2_desc: '건강검진 결과표는 대부분 전문 의학 용어와 수치 중심으로 작성되어 일반 사용자가 자신의 건강 상태를 정확히 이해하기 어렵습니다. 그 결과 관리가 필요한 신호를 놓치기도 합니다.',
    slide3_title: 'AI가 건강 데이터를 분석합니다',
    slide3_desc: 'CareLink는 건강검진 데이터를 AI로 분석하여 대사증후군 주요 지표와 건강 위험 요소를 파악하고 사용자가 이해하기 쉬운 형태로 건강 상태를 설명합니다.',
    slide4_title: '당신에게 맞는 건강 관리 방법',
    slide4_desc: 'CareLink는 개인의 건강 데이터를 기반으로 맞춤형 식단, 운동, 생활습관 개선 가이드를 제공합니다. 지속적인 건강 관리와 변화를 함께 만들어갑니다.',
    slide5_title: '지금 나의 건강 상태를 확인해보세요',
    slide5_desc: '건강검진 결과를 업로드하면 AI가 건강 상태를 분석하고 맞춤형 건강 관리 가이드를 제공합니다. 지금 CareLink와 함께 건강 관리를 시작해보세요.',
    startAnalysis: '건강 분석 시작하기',

    // 후기
    reviewTitle: '사용자 후기',
    reviews: [
      { name: '김OO', text: '드디어 건강검진 결과를 이해했어요! AI의 설명이 정말 명확하고 도움이 되었습니다.' },
      { name: '이XX', text: '인터페이스가 현대적이고 사용하기 쉽네요. 모든 분들께 강력히 추천합니다.' },
      { name: '박YY', text: '더 이상 의학 용어를 검색할 필요가 없어요. CareLink가 즉시 모든 것을 해결해 줍니다.' },
      { name: '최ZZ', text: '내 건강 관리에 더 자신감이 생겼어요. 정말 혁신적인 도구입니다.' },
    ],

    // 비디오 섹션
    videoTitle: '오늘의 건강 인사이트',
    videoDesc: '건강은 작은 생활 습관에서 시작됩니다.\n영상에서 소개하는 건강 관리 방법을 확인하고, CareLink에서 제공하는 개인 맞춤 건강 관리 팁도 함께 확인해보세요.',
    videoFeature1: '✓ 건강검진 데이터 기반 건강 분석',
    videoFeature2: '✓ 개인 맞춤형 영양 가이드',
    videoFeature3: '✓ 생활습관 개선 추천',
    customAnalysis: '맞춤형 분석 해보기 >',

    // 푸터 / 문의
    companyName: '(주)케어링크 헬스케어 서비스',
    address: '경기 수원시 팔달구 중부대로 100 4층',
    contactInfo: '전화: 02-1234-5678 | 이메일: support@carelink.health',
    contactTitle: '문의하기',
    emailPlaceholder: '이메일',
    messagePlaceholder: '메시지',
    sendBtn: '메시지 보내기',
    terms: '이용약관',
    privacy: '개인정보처리방침',
    copyright: '© Copyright 2026 CareLink Healthcare - All Rights Reserved',
    contactSuccess: '소중한 의견이 전달되었습니다!',
    contactFail: '전송에 실패했습니다. 다시 시도해주세요.',
    contactError: '서버와 연결할 수 없습니다.',
    contactValidation: '이메일과 메시지를 모두 입력해주세요.',

    // 업로드 페이지
    back: '뒤로가기',
    healthDataInput: '건강 데이터 입력',
    smartUpload: '스마트 업로드',
    smartUploadDesc: '검진 결과지 사진이나 PDF를 업로드하면 AI가 자동으로 수치를 정밀하게 추출합니다.',
    fileDragOrClick: '파일을 드래그하거나 클릭하세요',
    fileTypes: 'JPG, PNG, PDF (최대 10MB)',
    analysisProcess: '분석 프로세스',
    step1: '1. 구글 Vision OCR 텍스트 추출',
    step2: '2. Gemini 3.0 Flash 지표 분석',
    completed: '추출완료',
    waiting: '대기 중',
    dataInputTitle: '데이터 입력 및 확인',
    dataInputDesc: '빈 칸에 직접 정보를 입력하거나, 스마트 업로드 후 자동 추출된 결과가 맞는지 확인하고 빈 항목을 채워주세요.',
    aiSummaryTitle: 'AI 추출 요약',
    guestInfoTitle: '간단 정보 입력 (비회원)',
    guestInfoDesc: '정확한 AI 건강 분석을 위해 기본 신체 정보를 입력해주세요.',
    name: '이름',
    namePlaceholder: '예: 홍길동',
    age: '나이',
    agePlaceholder: '예: 35',
    gender: '성별',
    male: '남성',
    female: '여성',
    examYear: '검진 연도',
    height: '신장 (cm)',
    weight: '체중 (kg)',
    waist: '허리둘레 (cm)',
    bpSys: '수축기 혈압 (mmHg)',
    bpDia: '이완기 혈압 (mmHg)',
    glucose: '공복 혈당',
    tg: '중성 지방 (mg/dL)',
    hdl: 'HDL 콜레스테롤 (mg/dL)',
    ldl: 'LDL 콜레스테롤 (mg/dL)',
    ast: 'AST (U/L)',
    alt: 'ALT (U/L)',
    gammaGtp: '감마 GTP (U/L)',
    startAiBtn: 'AI 스마트 분석 시작하기',
    saveBtn: '최종 데이터 확인 및 저장',
    guestSavePrompt: '이 훌륭한 건강 분석 결과를 저장하시겠습니까? 저장을 위해 1분만에 회원가입을 완료해 보세요!',
    noFile: '파일이 업로드되지 않았습니다.',
    guestMissingInfo: '비회원 분석을 위해 이름과 나이를 입력해주세요.',
    sessionExpired: '세션이 만료되었습니다. 다시 로그인해주세요.',
    processingError: '처리 중 오류가 발생했습니다. 다시 시도해주세요.',

    // 로그인 페이지
    loginWelcome: '다시 오신 것을 환영합니다',
    loginSubtitle: '오늘도 당신의 건강 데이터를 확인해보세요',
    emailInput: '이메일 주소',
    passwordInput: '비밀번호',
    keepLogin: '로그인 유지',
    saveId: '아이디 저장',
    forgotPassword: '비밀번호 찾기',
    loginBtn: '로그인하기',
    checking: '확인 중...',
    noAccount: '아직 회원이 아니신가요?',
    quickSignup: '빠른 회원가입',
    loginFail: '로그인에 실패했습니다.',
    loginError: '로그인 중 오류가 발생했습니다.',

    // 회원가입 페이지
    signupTitle: '건강 관리를 시작해보세요',
    signupSubtitle: '30초면 충분합니다. 지금 바로 시작하세요.',
    fullName: '이름',
    fullNamePlaceholder: '홍길동',
    birthDate: '생년월일',
    signupMale: '남성',
    signupFemale: '여성',
    agreeAll: '전체 동의',
    agreeTerms: '이용약관 동의 (필수)',
    agreePrivacy: '개인정보 처리방침 동의 (필수)',
    agreeMarketing: '마케팅 정보 수신 동의 (선택)',
    createAccountBtn: '계정 만들기',
    hasAccount: '이미 계정이 있으신가요?',
    goLogin: '로그인하기',

    // 마이페이지
    dashboardTitle: '마이페이지',
    dashboardWelcome: (name) => `환영합니다, ${name}님. 오늘의 분석 리포트입니다.`,
    loadingMsg: '당신의 건강 데이터를 분석 중입니다...',
    navDashboard: '건강 대시보드',
    navReport: '검진 기록',
    navChatbot: 'AI 챗봇',
    aiComment: 'AI 코멘트',
    noDataTitle: '아직 분석된 데이터가 없습니다.',
    noDataDesc: '건강검진 결과지를 업로드하여 AI 분석을 받고 맞춤형 리포트와 액션 플랜을 받아보세요.',
    uploadDataBtn: '데이터 업로드하기',
    defaultAiMsg: '건강 데이터 분석 데이터가 충분하지 않습니다.',
    stableStatus: '안정적',
  },

  en: {
    // Common Navigation
    mypage: 'My Page',
    logout: 'Logout',
    login: 'Login',
    signup: 'Get Started',

    // Slider
    slide1_desc: 'CareLink is a smart healthcare service that analyzes health checkup data to help users easily understand their health conditions and manage them continuously.',
    slide2_title: 'Do you truly understand your health checkup results?',
    slide2_desc: 'Health checkup reports are mostly written in complex medical terms and numbers, making it hard for general users to understand their health status accurately. As a result, important health signals may be missed.',
    slide3_title: 'AI Analyzes Your Health Data',
    slide3_desc: 'CareLink uses AI to analyze health checkup data, identify key metabolic syndrome indicators and health risk factors, and explain your health status in an easy-to-understand way.',
    slide4_title: 'Health Management Tailored to You',
    slide4_desc: 'CareLink provides personalized diet, exercise, and lifestyle improvement guides based on your health data. We help you make lasting health changes together.',
    slide5_title: 'Check Your Health Status Right Now',
    slide5_desc: 'Upload your health checkup results and AI will analyze your health status and provide a personalized health management guide. Start managing your health with CareLink today.',
    startAnalysis: 'Start Health Analysis',

    // Reviews
    reviewTitle: 'User Reviews',
    reviews: [
      { name: 'Kim O.', text: 'I finally understood my health checkup results! The AI explanations were clear and very helpful.' },
      { name: 'Lee X.', text: 'The interface is modern and easy to use. I highly recommend it to everyone.' },
      { name: 'Park Y.', text: 'No need to search for medical terms anymore. CareLink solves everything instantly.' },
      { name: 'Choi Z.', text: 'I feel much more confident about managing my health. A truly innovative tool.' },
    ],

    // Video section
    videoTitle: "Today's Health Insights",
    videoDesc: "Good health starts with small daily habits.\nCheck out the health tips from the video, and discover personalized health management tips from CareLink.",
    videoFeature1: '✓ Health analysis based on checkup data',
    videoFeature2: '✓ Personalized nutrition guide',
    videoFeature3: '✓ Lifestyle improvement recommendations',
    customAnalysis: 'Try Customized Analysis >',

    // Footer / Contact
    companyName: 'CareLink Healthcare Service, Inc.',
    address: '4F, 100 Jungbu-daero, Paldal-gu, Suwon, Gyeonggi-do',
    contactInfo: 'Tel: 02-1234-5678 | Email: support@carelink.health',
    contactTitle: 'Contact Us',
    emailPlaceholder: 'Email',
    messagePlaceholder: 'Message',
    sendBtn: 'Send Message',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    copyright: '© Copyright 2026 CareLink Healthcare - All Rights Reserved',
    contactSuccess: 'Your message has been delivered!',
    contactFail: 'Failed to send. Please try again.',
    contactError: 'Unable to connect to the server.',
    contactValidation: 'Please enter both email and message.',

    // Upload page
    back: 'Go Back',
    healthDataInput: 'Health Data Input',
    smartUpload: 'Smart Upload',
    smartUploadDesc: 'Upload a photo or PDF of your checkup results and AI will automatically extract the values with precision.',
    fileDragOrClick: 'Drag & drop or click to select a file',
    fileTypes: 'JPG, PNG, PDF (max 10MB)',
    analysisProcess: 'Analysis Process',
    step1: '1. Google Vision OCR Text Extraction',
    step2: '2. Gemini 3.0 Flash Indicator Analysis',
    completed: 'Done',
    waiting: 'Waiting',
    dataInputTitle: 'Data Input & Review',
    dataInputDesc: 'Enter data directly, or verify the auto-extracted results after Smart Upload and fill in any missing fields.',
    aiSummaryTitle: 'AI Extraction Summary',
    guestInfoTitle: 'Basic Info (Guest)',
    guestInfoDesc: 'Please enter your basic physical information for accurate AI health analysis.',
    name: 'Name',
    namePlaceholder: 'e.g. John Doe',
    age: 'Age',
    agePlaceholder: 'e.g. 35',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    examYear: 'Exam Year',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    waist: 'Waist Circumference (cm)',
    bpSys: 'Systolic BP (mmHg)',
    bpDia: 'Diastolic BP (mmHg)',
    glucose: 'Fasting Blood Glucose',
    tg: 'Triglycerides (mg/dL)',
    hdl: 'HDL Cholesterol (mg/dL)',
    ldl: 'LDL Cholesterol (mg/dL)',
    ast: 'AST (U/L)',
    alt: 'ALT (U/L)',
    gammaGtp: 'Gamma-GTP (U/L)',
    startAiBtn: 'Start AI Smart Analysis',
    saveBtn: 'Confirm & Save Final Data',
    guestSavePrompt: 'Would you like to save this great health analysis result? Sign up in just 1 minute to save it!',
    noFile: 'No file has been uploaded.',
    guestMissingInfo: 'Please enter your name and age for guest analysis.',
    sessionExpired: 'Session expired. Please log in again.',
    processingError: 'An error occurred. Please try again.',

    // Login page
    loginWelcome: 'Welcome Back',
    loginSubtitle: 'Check your health data today as well.',
    emailInput: 'Email Address',
    passwordInput: 'Password',
    keepLogin: 'Stay logged in',
    saveId: 'Save ID',
    forgotPassword: 'Forgot Password',
    loginBtn: 'Log In',
    checking: 'Checking...',
    noAccount: "Don't have an account?",
    quickSignup: 'Sign up now',
    loginFail: 'Login failed.',
    loginError: 'An error occurred during login.',

    // Signup page
    signupTitle: 'Start Managing Your Health',
    signupSubtitle: 'Only 30 seconds. Get started now.',
    fullName: 'Full Name',
    fullNamePlaceholder: 'John Doe',
    birthDate: 'Date of Birth',
    signupMale: 'Male',
    signupFemale: 'Female',
    agreeAll: 'Agree to all',
    agreeTerms: 'Terms of Service (Required)',
    agreePrivacy: 'Privacy Policy (Required)',
    agreeMarketing: 'Marketing Consent (Optional)',
    createAccountBtn: 'Create Account',
    hasAccount: 'Already have an account?',
    goLogin: 'Log In',

    // My page
    dashboardTitle: 'My Page',
    dashboardWelcome: (name) => `Welcome, ${name}. Here is your analysis report for today.`,
    loadingMsg: 'Analyzing your health data...',
    navDashboard: 'Health Dashboard',
    navReport: 'Exam Records',
    navChatbot: 'AI Chatbot',
    aiComment: 'AI Comment',
    noDataTitle: 'No analyzed data yet.',
    noDataDesc: 'Upload your health checkup results to receive AI analysis and get a personalized report and action plan.',
    uploadDataBtn: 'Upload Data',
    defaultAiMsg: 'Insufficient health data for analysis.',
    stableStatus: 'Stable',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('ko');
  const t = translations[lang];
  const toggleLang = () => setLang(prev => (prev === 'ko' ? 'en' : 'ko'));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
